plugins {
    id 'com.android.library'
}

android {
    /*
    signingConfigs {
        release {
            storeFile file('/home/tony/TAF/APPS/BookPlayer ressources/keystore/bbb.jks')
            storePassword '***'
            keyAlias 'key0'
            keyPassword '***'
        }
    }

     */
    compileSdk 34

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 34

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
//        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled true // Enables code shrinking, obfuscation, and optimization
            shrinkResources false // not possible for library

//            proguardFiles getDefaultProguardFile(
//                    'proguard-android-optimize.txt'),
//                    'proguard-rules.pro'

            //signingConfig signingConfigs.release
            //debuggable true
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    namespace 'com.driot.tonylib'
}

dependencies {

    //implementation 'androidx.appcompat:appcompat:1.6.1'
    //implementation 'com.google.android.material:material:1.9.0'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}