plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
    id "dagger.hilt.android.plugin"
}

android {

    compileSdk = 35
    namespace = 'com.driot.bookplayer'

    defaultConfig {
        applicationId = "com.driot.bookplayerfull"  //CHANGE HERE : ORIGINAL - FULL
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        //testInstrumentationRunnerArguments clearPackageData: "false"

        buildConfigField "String", "RADIO_PROXY_BASE_URL", "\"https://radio.driot.com\""
        buildConfigField "String", "LIBRIVOX_PROXY_BASE_URL", "\"https://librivox.driot.com\"";
        buildConfigField "String", "PODCASTINDEX_BASE_URL", "\"https://steep-hat-11ff.adriot.workers.dev/podcastindex/\""
        buildConfigField "String", "PIXABAY_BASE_URL", "\"https://steep-hat-11ff.adriot.workers.dev\""

        buildConfigField "String", "APP_TOKEN", "\"bookplayer_petit_mais_costaud\""

        //  16   = android 4.1 Jelly Bean    2012
        //  19   = android 4.4 KitKat        2013       --> support dropped 2023 (Play store hs)
        //  21   = android 5.0 Lollipop      2014       --> google app are not updated since 2021...
        //  23   = android 6.0 Marshmallow   2015
        //  24   = android 7.0 Nougat        2016
        //  26   = android 8.0 Oreo          2017   VERSION_CODES.O      <--------- Main test article (Huawei), OK
        //  28   = android 9.0
        //  30   = android 11.0
        // 31-32 = android 12.0
        //  33   = android 13.0 Tiramisu
        //  34   = android 14.0 Upside Down Cake        2023
        //  35   = android 15.0 Vanilla Ice Cream       2025

        minSdk = 26
        //24 seems to be minimum for ZipFile
        //note : 26 needed for special mediaPlayer.seekTo (m4b)
        //note : 26 needed for NotificationChannel
        //note : 26 needed for xml adaptable icons
        //note : 26 needed for paddingHorizontal in xml files   ====> maybe it is why it does not work on android 7 ?

        targetSdk = 35

        /////////////////////////////////////////////////////////////////////////
        /////////////////////////////////////////////////////////////////////////
        versionCode = 264
        versionName = "264 - Eclipse Meerkat"
        /////////////////////////////////////////////////////////////////////////
        /////////////////////////////////////////////////////////////////////////

        //signingConfig = signingConfigs.debug

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["room.schemaLocation": "$projectDir/schemas".toString()]
            }
        }

        androidResources {
            generateLocaleConfig = true
        }

        sourceSets {
            main {
                res.srcDirs = ['src/main/res', 'src/main/res-flags']
            }
        }

    }
/*
    signingConfigs {
        release {
            //storeFile file('/home/tony/TAF/APPS/BookPlayer ressources/keystore/bbb.jks')
            //storeFile file('C:/Users/adrio/StudioProjects/keystore/ccc.jks')
            storeFile file('C:/Users/adrio/StudioProjects/BookPlayer ressources/keystore/bbb.jks')
            storePassword '****'
            keyAlias 'key0'
            keyPassword '****'
        }
    }
*/
    testOptions {
        animationsDisabled = true
        execution 'ANDROIDX_TEST_ORCHESTRATOR'
        unitTests {
            includeAndroidResources = true
            returnDefaultValues = true
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix = ".debug"
            versionNameSuffix = "-debug"
            resValue "string", "app_name", "DEBUG BookPlayer"

            // Make tests debuggable
            debuggable = true
            enableUnitTestCoverage false
            enableAndroidTestCoverage false

            /*
            minifyEnabled = true
            shrinkResources = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                    'proguard-rules.pro'

             */
        }
        release {
            // Enables code shrinking, obfuscation, and optimization for only
            // your project's release build type.
            minifyEnabled = true //R8

            // Enables resource shrinking, which is performed by the
            // Android Gradle plugin.
            shrinkResources = true //Progard

            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'),
                    'proguard-rules.pro'

            //signingConfig signingConfigs.release
            //debuggable true
        }

    }
    testFixtures {
        enable = true
    }
    buildFeatures {
        buildConfig = true   // set to false if you don't use BuildConfig in this module
        resValues = true     // required because debug build type defines custom resValue entries
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

}

configurations.implementation {
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'  // to avoid error : Duplicate class kotlin....found in modules jetified-kotlin-stdlib-1.8.10 (org.jetbrains.kotlin:kotlin-stdlib:1.8.10) and jetified-kotlin-stdlib-jdk8-1.7.20 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.20)
}

dependencies {
    implementation 'androidx.core:core:1.16.0' //needs sdk 36

    implementation 'org.apache.commons:commons-io:1.3.2'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.annotation:annotation:1.9.1'

    implementation 'androidx.documentfile:documentfile:1.1.0'

    implementation 'com.google.firebase:firebase-crashlytics:20.0.4'
    implementation platform('com.google.firebase:firebase-bom:34.9.0')
    implementation 'com.google.firebase:firebase-analytics'

    implementation 'com.google.code.gson:gson:2.13.2'
    implementation 'org.jsoup:jsoup:1.22.1'
    implementation 'com.squareup.retrofit2:retrofit:3.0.0'
    implementation 'com.squareup.retrofit2:converter-gson:3.0.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:5.3.2'
    implementation 'com.github.bumptech.glide:glide:5.0.5'
    implementation 'com.googlecode.mp4parser:isoparser:1.1.22'

    implementation "androidx.work:work-runtime:2.11.1"

    implementation "androidx.room:room-runtime:2.8.4"
    annotationProcessor "androidx.room:room-compiler:2.8.4"

    implementation 'androidx.media:media:1.7.1'
    implementation "androidx.media3:media3-exoplayer:1.9.2"
    //implementation "androidx.media3:media3-ui:1.3.1"        // if you use PlayerView

    implementation "org.apache.commons:commons-compress:1.28.0"
    implementation "org.tukaani:xz:1.11" //7z

    implementation 'org.zwobble.mammoth:mammoth:1.5.0'

    implementation "com.google.dagger:hilt-android:2.59.1"
    annotationProcessor "com.google.dagger:hilt-compiler:2.59.1"

    // Nearby Connections for phone-to-phone sharing
    implementation 'com.google.android.gms:play-services-nearby:19.3.0'

    androidTestUtil "androidx.test:orchestrator:1.6.1"

    // ---- Unit tests (JVM) ----
    testImplementation "junit:junit:4.13.2"

    // ---- Instrumented tests (device/emulator) ----
    androidTestImplementation "androidx.test:core:1.7.0"
    androidTestImplementation "androidx.test:rules:1.7.0"
    androidTestImplementation "androidx.test.ext:junit:1.3.0"          // AndroidJUnit4 + ActivityScenarioRule
    androidTestImplementation "androidx.test:runner:1.7.0"             // test runner
    androidTestImplementation "androidx.test.espresso:espresso-core:3.7.0"
    androidTestImplementation "androidx.test.espresso:espresso-contrib:3.7.0"
    androidTestImplementation "androidx.test.uiautomator:uiautomator:2.3.0"
    androidTestImplementation "com.google.truth:truth:1.4.5"
    androidTestImplementation "androidx.work:work-testing:2.11.1"

    androidTestImplementation(project(path: ":app"))
}
