plugins {
    id 'com.android.application'
}

android {
    /*
    signingConfigs {
        release {
            storeFile file('/home/tony/TAF/APPS/BookPlayer ressources/keystore/bbb.jks')
            storePassword '****'
            keyAlias 'key0'
            keyPassword '****'
        }
    }

     */
    compileSdkVersion 33

    defaultConfig {
        applicationId "com.driot.bookplayer"
        minSdkVersion 26 //  23 = android 6.0 Marshmallow 2015 // 26 = android 8.0 - Oreo - 2017
        targetSdkVersion 33 //31-32 =  = android 11.0       //  30 = android 11.0

        versionCode 25
        versionName "25 - LockedPhoneNotification"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        signingConfig signingConfigs.debug

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["room.schemaLocation": "$projectDir/schemas".toString()]
            }
        }
    }
    buildTypes {
        release {
            // Enables code shrinking, obfuscation, and optimization for only
            // your project's release build type.
            minifyEnabled false

            // Enables resource shrinking, which is performed by the
            // Android Gradle plugin.
            shrinkResources false

            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'),
                    'proguard-rules.pro'
            //signingConfig signingConfigs.release
            //debuggable true
        }

    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

}


dependencies {

    implementation 'org.apache.commons:commons-io:1.3.2'
    implementation 'androidx.documentfile:documentfile:1.0.1'
    implementation 'com.google.android.play:core:1.10.3'
    implementation project(path: ':tonyLib')

    //implementation 'com.nbsp:library:filepicker:2.4.1'
    //implementation 'com.nbsp:library:filepicker:1.2.1'
    //implementation 'com.github.arteaprogramar:Android_MaterialFilePicker:1.0.0'
    //implementation 'com.nabinbhandari.android:filepicker:2.2.2'

    //implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.6.1' //snackBar, recyclerView
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.0'
    implementation "androidx.room:room-runtime:2.4.3"
    implementation 'androidx.core:core:1.10.1'
    implementation 'androidx.media:media:1.6.0'
    implementation 'androidx.annotation:annotation:1.7.0'
    annotationProcessor "androidx.room:room-compiler:2.4.3"
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
}