package com.driot.bookplayer.redownload;

import android.content.Context;
import android.net.Uri;

import androidx.work.Data;
import androidx.work.ExistingWorkPolicy;
import androidx.work.OneTimeWorkRequest;
import androidx.work.WorkManager;

import com.driot.bookplayer.db.AppDatabase;
import com.driot.bookplayer.db.BookSource;
import com.driot.bookplayer.db.Folder;
import com.driot.bookplayer.db.ZikFile;
import com.driot.bookplayer.helpers.StorageHelper;
import com.driot.bookplayer.helpers.UriHelper;
import com.driot.bookplayer.podcasts.PodcastRedownload;

import static com.driot.bookplayer.utils.log.LoggerStaticHelper.*;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

/**
 * Fetches a book's audio again, in place, after its files went missing (a backup that skipped
 * them, a deleted folder...). The Folder and ZikFile rows are kept as they are, so listening
 * progress, bookmarks and ids survive - only the files come back.
 * <p>
 * Two sources: podcast episodes (each episode's own enclosure address, full flavor only) and
 * BookSource addresses (Librivox, direct links). Gutenberg ebooks are deliberately not covered:
 * their chapters are generated by a split step, not downloaded as-is.
 */
public final class RedownloadHelper {

    public static final String KEY_FOLDER_ID = "folder_id";

    private RedownloadHelper() {
    }

    public static class MissingTrack {
        public final ZikFile zik;
        public final File dest;

        MissingTrack(ZikFile zik, File dest) {
            this.zik = zik;
            this.dest = dest;
        }
    }

    /** Must run off the main thread (database access). */
    public static boolean isRedownloadable(Context context, long folderId) {
        AppDatabase db = AppDatabase.getDatabase(context);
        if (db.bookSourceDao().getRedownloadableFolderIds().contains(folderId)) {
            return true;
        }
        return PodcastRedownload.isRedownloadable(context, folderId);
    }

    /** Must run off the main thread. */
    public static boolean hasMissingFiles(Context context, long folderId) {
        List<ZikFile> zikFiles = AppDatabase.getDatabase(context).zikFileDao().getZikFiles(folderId);
        for (ZikFile zf : zikFiles) {
            if (UriHelper.resolvePlayableUri(context, zf) == null) {
                return true;
            }
        }
        return false;
    }

    /** Folders that can be fetched again and are missing at least one file. Must run off the
     *  main thread. */
    public static List<Long> findFoldersToRedownload(Context context) {
        AppDatabase db = AppDatabase.getDatabase(context);
        java.util.Set<Long> candidates = new java.util.LinkedHashSet<>(db.bookSourceDao().getRedownloadableFolderIds());
        candidates.addAll(PodcastRedownload.folderIds(context));
        List<Long> out = new ArrayList<>();
        for (long id : candidates) {
            if (hasMissingFiles(context, id)) {
                out.add(id);
            }
        }
        return out;
    }

    /** Where each missing track of the folder has to be written. A track keeps the path the
     *  database has when that place is still writable; a track whose place is gone (say the SD
     *  card of the old device) is moved to a folder in BookPlayer's own storage and its path
     *  rewritten. Decided per track: one book can have tracks in several places. Must run off
     *  the main thread. */
    public static List<MissingTrack> prepareMissingTracks(Context context, long folderId) {
        AppDatabase db = AppDatabase.getDatabase(context);
        Folder folder = db.folderDao().getById(folderId);
        List<ZikFile> zikFiles = db.zikFileDao().getZikFiles(folderId);
        List<MissingTrack> out = new ArrayList<>();
        if (folder == null || zikFiles.isEmpty()) {
            return out;
        }

        File fallbackDir = null;
        for (ZikFile zf : zikFiles) {
            if (UriHelper.resolvePlayableUri(context, zf) != null) {
                continue; // still there
            }
            String plain = plainPath(zf.getPath());
            File dir = plain == null ? null : new File(plain).getParentFile();
            if (dir != null && usableDir(dir)) {
                out.add(new MissingTrack(zf, new File(plain)));
                continue;
            }
            if (fallbackDir == null) {
                fallbackDir = createFallbackDir(context, folder);
                if (fallbackDir == null) {
                    myLogE("prepareMissingTracks: no place to write folder " + folderId);
                    continue;
                }
            }
            String name = plain != null ? new File(plain).getName() : zf.getName();
            File dest = new File(fallbackDir, name);
            zf.setPath(dest.getAbsolutePath());
            db.zikFileDao().update(zf);
            out.add(new MissingTrack(zf, dest));
        }

        if (fallbackDir != null) {
            File folderDir = rawFolderDir(folder.getPath());
            if (folderDir == null || !usableDir(folderDir)) {
                folder.setPath(fallbackDir.getAbsolutePath());
                db.folderDao().update(folder);
            }
        }
        return out;
    }

    private static boolean usableDir(File dir) {
        return (dir.isDirectory() || dir.mkdirs()) && dir.canWrite();
    }

    private static File createFallbackDir(Context context, Folder folder) {
        String safe = folder.getName() == null ? "book" : folder.getName().replaceAll("[\\\\/:*?\"<>|]", "_");
        File dir = new File(StorageHelper.getUnzipFolder(context), safe + "_" + folder.getId());
        return dir.isDirectory() || dir.mkdirs() ? dir : null;
    }

    private static File rawFolderDir(String folderPath) {
        String p = plainPath(folderPath);
        return p == null ? null : new File(p);
    }

    /** The plain file path behind a stored track path: file:// addresses are percent-encoded
     *  ("my%20book/track%201.mp3"), raw paths are used as they are. Null for content:// (SAF). */
    private static String plainPath(String path) {
        if (path == null || path.startsWith("content://")) {
            return null;
        }
        return path.startsWith("file://") ? Uri.parse(path).getPath() : path;
    }

    private static File rawDir(String path) {
        String p = plainPath(path);
        return p == null ? null : new File(p).getParentFile();
    }

    /** Queues the download. Safe from any thread; the work itself is asynchronous. */
    public static void start(Context context, long folderId) {
        Context app = context.getApplicationContext();
        AppDatabase.databaseWriteExecutor.execute(() -> {
            if (PodcastRedownload.isRedownloadable(app, folderId)) {
                PodcastRedownload.enqueue(app, folderId);
                return;
            }
            BookSource bs = AppDatabase.getDatabase(app).bookSourceDao().getByFolderId(folderId);
            if (bs == null || bs.source_url == null || bs.source_url.isEmpty()) {
                myLogW("start: no download address for folder " + folderId);
                return;
            }
            OneTimeWorkRequest request = new OneTimeWorkRequest.Builder(RedownloadBookWorker.class)
                    .setInputData(new Data.Builder().putLong(KEY_FOLDER_ID, folderId).build())
                    .build();
            WorkManager.getInstance(app).enqueueUniqueWork("REDOWNLOAD_BOOK_" + folderId,
                    ExistingWorkPolicy.KEEP, request);
        });
    }
}
